### ISSUE TITLE
Logging actions to Diary

### ISSUE THREAD

**Issue by linuxcaffe** [teranex/vimwiki-tasks#17]
One of the things that I think would be great, in melding tw and vimwiki functionality, is the chance to log all relevant activities to my vimwiki diary file for the day; tasks added, completed and deleted, as well as the usual treatment, if such actions were automatically logged to the days diary, would enhance the record of the day.

standardized, foldable header with 

``` md
= tasks = 
== added ==
   - [ ] do laundry
== completed ==
   - [X] feed cat
```

And there's no reason (?) these tasks couldn't be just as actionable from within that diary file.

Because taskwarrior tasks all have added, complete, deleted dates, a GenDiaryActions function could retroactively create these entries (and diary files, if needed) from past actions. I would draw the line at modifications, I don't really need to know that I added a tag that day.

I would also like to see other activities in other programs logged in the same way, 
but that's a different kettle o fish!

**Comment by linuxcaffe** [comment]
There's probably an argument for including tasks scheduled on that day, if any, under another heading.

``` md
= tasks =
== added ==
== completed ==
== deleted ==
== due today ==
```

even if (especially if) they are not completed on that day.

**Comment by teranex** [comment]
I can see the use for this. But it is very specific to ones requirements. Which tasks should be included? How should the layout of the file look? etc. I guess everybody will have a different preference so just adding one report would not be very useful for 99% of users.
I do think however that the basic building-blocks to create such a report are already available. You
could for example add something like this to your .vimrc or ftplugin/vimwiki.vim (this is untested vimscript so it will probably create a tiny black hole if you run it):

``` vim
function! GenerateReport()
  normal i= tasks =
  normal i== added ==
  InsertTasks entry.after:yesterday
  normal i== completed ==
  InsertTasks status:completed end.after:yesterday
  " and so on...
endfunction

command! InsertDairyTaskLog call GenerateReport()
```

And then you could open your dairy and run `:InsertDairyTaskLog` and you should get the entire
report (or see a tiny black hole grow, which is also ince :) )

**Comment by linuxcaffe** [comment]
Firstly, thanks for the above examples, I'll take them home and give them a whirl. 

Secondly I must respectfully disagree that "it is very specific to ones requirements", as the feature was designed specifically for General Audiences. It logs all of the "actions" you take with tw that day: add, complete, delete, and it lists the things you were supposed to do that day. That's not an "edge case", and isn't that the very sort of things you would want to have recorded on that day?
As to the layout, I just went for the above elements in the simplest possible arrangement under headings, where on the page doesn't matter, it's foldable down to one line; "tasks", and my diary pages are presently under-used anyways. 

Thirdly, as I can see that our ideas of what might make an "ideal" taskwiki are somhat divergent, maybe I should start up a fork, and you might help me do crazy things you would never do to your own branch, sound like a plan? 

Thanks for all your help, past and future, and for all your other fine contributions!
