### ISSUE TITLE
add + abbreviations

### ISSUE THREAD

**Issue by linuxcaffe** [teranex/vimwiki-tasks#20]
Just a kooky thought here, a "task add" routine within vim provides an opportunity to use vim abbreviations. This enables something that has been requested for years; add something in a short-form that get's expanded before saving. 

example:

```
$ task add get tps @work 
```

becomes

```
$ task add get Training Progress Report proj:train pri:h +work
```

**Comment by teranex** [comment]
You can already do this with standard Vim functionality. One possible method:
create a file `~/.vim/after/ftplugin/vimwiki.vim`. This file will be executed by Vim whenever a file is detected to be a vimwiki file (after the default vimwiki file is processed). In the file add abbreviations like this:

``` vim
cabbrev <buffer> tps Training Progress Report
cabbrev <buffer> @work proj:train pri:h +work
```

Now whenever you type 'tps<space>' in commandline while in a vimwiki file Vim will immediately expand it to 'Training Progress Report'. I'm not sure if @work would work, but _work would work. You can also define abbreviations with 'iabbrev' for insert mode etc (vim :help has more info).

Besides, as far as I know the Taskwarrior aliasses can also be used for this:
`alias.tps=Training Progress Report`
`task add tps`
would for afaik.
