### ISSUE TITLE
don't bring completed ones back to %%Tasklist

### ISSUE THREAD

**Issue by linuxcaffe** [teranex/vimwiki-tasks#24]
I think the fact that a %%TaskList doesn't remove completed tasks automatically, is a feature! Good behavior!

But I'd like to be able to manually delete them from a listing, and have them stay gone. I don't want to "delete the completed ones" or anything, but hoping there was a way that the sync process could (optionally?) not remove them automatically, but also not re-import completed or deleted tasks once manually removed.

**Comment by teranex** [comment]
Why not add `status:pending` as a condition in that case? I don't really see any other way how it could be done.

**Comment by linuxcaffe** [comment]
reasonable! how about this; a settings option for InsertTasks, that would be added to the %%TaskList query, like 

```
let vimwiki_task_insert_filter = 'status:pending -test'
```

?

**Comment by teranex** [comment]
Ah, but in that case you can use the 'vimwiki_tasks_report'  option, which let you specify the report which should be used to get the tasklist in combination with the additional parameters from the Tasklist query.  It defaults to 'all'  but you can use any tw report to set a default filter. 
I really should write the documentation :-)

**Comment by linuxcaffe** [comment]
let g:vimwiki_tasks_report = 'list', in my vimrc,
didn't change anything.. am I doing it wrong?

**Comment by linuxcaffe** [comment]
Instead of "all", could vimwiki_tasks_report default to rc.default.command ? or failing that, "list" is a better default than "all", imho, but your own default command is better still, unless otherwise specified.  :)

**Comment by teranex** [comment]
I just tested myself by adding;

``` vim
let g:vimwiki_tasks_report = 'list'
```

in my .vimrc and it works. Without the config option when doing `InsertTasks limit:100` it inserts all tasks including completed ones. With the option set the same `InsertTasks limit:100` inserts only pending tasks.
I choose to default to 'all' because it give the broadest filter by default.

**Comment by linuxcaffe** [comment]
funny, that same line in _my_ .vimrc seems to have no affect, I see completed tasks either way :-/
